name: daesim2-analysis
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - importlib_metadata
  - ipython
  - jupyter
  - jupytext
  - matplotlib>=2.2.5
  - nb_black
  - notebook
  - pandas>=1.4.4
  - pip
  - pip:
    - git+https://github.com/NortonAlex/DAESIM@cb59514c392d63bf2ac32594ce52e1a4604b76e2#egg=daesim
  - scipy>=1.9.1
  - numpy
  - xarray
  - netCDF4
  - SALib
