name: daesim2-analysis
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - importlib_metadata
  - ipython
  - jupyter
  - jupytext
  - matplotlib>=2.2.5
  - nb_black
  - notebook
  - pandas>=1.4.4
  - pip
  - pip:
    - git+https://github.com/NortonAlex/DAESIM@6c6e0e93ad7909b8355268a4c7b6307396251173#egg=daesim
  - scipy>=1.9.1
  - numpy
  - xarray
  - netCDF4
  - SALib
